[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/monitor"
  to = "/.netlify/functions/monitor"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200



